apiVersion: v1
kind: Service
metadata:
  name: laravel-app # This name will be used by Nginx to communicate with PHP-FPM
  labels:
    app: laravel-app
spec:
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 9000 # Service port
      targetPort: 9000 # Container port
  type: ClusterIP # Internal service, only accessible within the cluster
