apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-secret
type: Opaque # Use type Opaque for general purpose secrets
stringData: # Use stringData to provide unencoded values; Kubernetes will base64 encode them
  DB_CONNECTION: "mysql"
  DB_DATABASE: yemdaro_db
  DB_USERNAME: laravel
  DB_PASSWORD: laravel
  DB_HOST: mysql-db # This should match the name of your MySQL Service in Kubernetes
  DB_PORT: "3306" # Port for MySQL
  APP_NAME: "Laravel"
  APP_ENV: "local"
  APP_KEY: "base64:M9nHLWjcAwG+N9XlVwcQnTmgn2Y9j/sjL9hVc4Rx2yI: "
  APP_DEBUG: "true"
  APP_URL: "http://localhost"
  APP_LOCALE: "en"
  APP_FALLBACK_LOCALE: "en"
  APP_FAKER_LOCALE: "en_US"

  APP_MAINTENANCE_DRIVER: "file"
  # APP_MAINTENANCE_STORE: "database"

  PHP_CLI_SERVER_WORKERS: "4"

  BCRYPT_ROUNDS: "12"

  LOG_CHANNEL: "stack"
  LOG_STACK: "single"
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: "debug"

  SESSION_DRIVER: "database"
  SESSION_LIFETIME: "120"
  SESSION_ENCRYPT: "false"
  SESSION_PATH: "/"
  SESSION_DOMAIN: "null"

  BROADCAST_CONNECTION: "log"
  FILESYSTEM_DISK: "local"
  QUEUE_CONNECTION: "database"

  CACHE_STORE: "database"
  # CACHE_PREFIX:" "

  MEMCACHED_HOST: "127.0.0.1"

  REDIS_CLIENT: "phpredis"
  REDIS_HOST: "127.0.0.1"
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

  MAIL_MAILER: "log"
  MAIL_SCHEME: "null"
  MAIL_HOST: "127.0.0.1"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MAIL_PASSWORD: "null"
  MAIL_FROM_ADDRESS: "hello@example.com"
  MAIL_FROM_NAME: "laravel-app"

  # AWS_ACCESS_KEY_ID:" "
  # AWS_SECRET_ACCESS_KEY:" "
  # AWS_DEFAULT_REGION: "us-east-1"
  # AWS_BUCKET:" "
  # AWS_USE_PATH_STYLE_ENDPOINT: "false"

  VITE_APP_NAME: "laravel-app"

  # Add other sensitive Laravel environment variables here, e.g., APP_KEY, JWT_SECRET
  # APP_KEY: SomeRandomStringForLaravel
  # JWT_SECRET: AnotherSecretKey
