apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db-deployment
  labels:
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-db
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env: # For production, use Kubernetes Secrets for sensitive data like passwords
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "laravel"
            - name: MYSQL_USER
              value: "laravel"
            - name: MYSQL_PASSWORD
              value: "laravel"
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql # Default MySQL data directory
          # Add readiness and liveness probes for production
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-data-pvc
