apiVersion: v1
kind: Service
metadata:
  name: nginx-webserver # This is the service exposing Nginx
  labels:
    app: nginx-webserver
spec:
  selector:
    app: nginx-webserver
  ports:
    - protocol: TCP
      port: 80 # Service port (internal to cluster or for LoadBalancer)
      targetPort: 80 # Container port
      nodePort:
        30081 # Exposed on each node at port 30081 (arbitrary high port, within 30000-32767 range)
        # Matches your docker-compose 8100 external port.
  type:
    NodePort # Exposes the service on a static port on each Node's IP.
    # For cloud environments, consider 'LoadBalancer' type for external IP.
